/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\airplane\model.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Plane(props) {
  const { nodes, materials } = useGLTF("./models/airplane/model.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.PUSHILIN_Plane_Circle000.geometry}
        material={materials.plane}
      />
      <mesh
        geometry={nodes.PUSHILIN_Plane_Helix.geometry}
        material={materials.plane}
        position={[1.09, 0.23, 0]}
      />
    </group>
  );
}

useGLTF.preload("./models/airplane/model.glb");
